### ISSUE TITLE
Make game start centered on player's base instead of top left of map

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/PlymouthColdWar#2]
Should be able to use function:

`Player[0].CenterViewOn(x + X_, y + Y_);`

**Comment by DanRStevens** [comment]
Yes.

Related, I recall OP2Helper had a `CenterViewOnPlayerCC()` method. I also recall something about having BaseBuilder automatically center the view on the player's starting location, though I don't remember if it was implemented.
