### ISSUE TITLE
Mission hangs soon after AI player is attacked

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/PlymouthColdWar#3]
It appears base defense is separated into zones. The Tokamaks at the top of the base and defending units can be attacked without issue. The hang triggers soon after attacking the units defending the common mine just south of the Tokamaks. Attacking the mine itself is not necessary.

The game becomes unresponsive but does not close or report an error. This behaviour happens when compiled in debug or release mode. It also occurs both with the Visual Studio debugger attached and without the debugger attached.

There is a decent delay after attacking the units before the crash happens. Perhaps it is caused by an update to replenish the units or a delayed state change in the AI's defense posture. 

Quick way to test is add the following code to the InitProc and then attack the enemy base. 

```C++
Unit unit;
for (int i = 0; i < 32; ++i) {
	TethysGame::CreateUnit(unit, map_id::mapLynx, LOCATION(50 + X_, 5 + Y_), 0, map_id::mapThorsHammer, 0);
}
```

**Comment by DanRStevens** [comment]
If the game hangs, it's quite possibly stuck in an infinite loop, or perhaps a slow loop that is iterating many more times than expected. Either way, you can more or less assume you have slow code.

If you have slow code, and you pause the code in a debugger, there is an increased chance the code will be paused within the slow section. It does after all take the most amount of runtime. This means the slow method should be somewhere on your call stack (it may have called one of many subfunctions, so might not be the current function). By repeatedly pausing the app and examining the callstack you can quite quickly narrow down the slow section of code. Each call stack sample should be weighted towards the slow code, so with enough sampling iterations, the chance of catching the slow code jumps up quite quickly.

In this case, the slow section is probably the buggy section that causes the hang.

----

With that said, I suspect some of OP2's AI group code is a bit buggy.

**Comment by DanRStevens** [comment]
From our earlier OllyDbg pair programming sessions today, the game does indeed get stuck in an infinite loop at address `0042726D`. This occurs in an undocumented method. The loop makes repeated calls to `RandomNumberGenerator.Rand(int range)`.

Tracing up the call stack, we came to an `ScStub:Group:BuildGroup` member function, which at address `425d20` calls out to undocumented code, which leads to the infinite loop.

**Comment by DanRStevens** [comment]
I took some time to document the method with the hanging loop at address `425d20`, as well as methods leading up to it so the data structures could be understood.

The code relates to prioritizing and building military vehicles to reinforce another group. The calling code builds a list of possible vehicle targets, along with priority weightings for which one should be selected.

In the method that hangs, the loop randomly selects a `targetInfo` struct (a vehicle it might build), using a priority weighting. It then checks the `targetInfo` struct's reference to a `recordedVehGroup` struct (a group to reinforce). If the `recordedVehGroup` struct has a `unitIndex` value set, it ignores the `targetInfo` selection, and loops trying to find another one. The hang appears to be caused by the `unitIndex` value being set for all referenced `recordedVehGroup` structs, and so all selections are ignored, and the code loops indefinitely.

I have not yet determined what the `unitIndex` represents. I'll look into that in a future debugging session.

**Comment by DanRStevens** [comment]
Call this a hunch, but what if we bumped up the minimum priority values in the following from 0 to 1:
```
    // Set reinforce info
    saveData.aiBuildGrp.RecordVehReinforceGroup(saveData.aiDefGrp[0], 0);
    saveData.aiBuildGrp.RecordVehReinforceGroup(saveData.aiDefGrp[1], 5000); // Very high priority; it's the lab
    saveData.aiBuildGrp.RecordVehReinforceGroup(saveData.aiDefGrp[2], 5000); // Also high; the CC
    saveData.aiBuildGrp.RecordVehReinforceGroup(saveData.aiDefGrp[3], 5000); // Factories
    saveData.aiBuildGrp.RecordVehReinforceGroup(saveData.aiDefGrp[4], 0);
    saveData.aiBuildGrp.RecordVehReinforceGroup(saveData.aiDefGrp[5], 0);
    saveData.aiBuildGrp.RecordVehReinforceGroup(saveData.aiDefGrp[6], 0);
```

The weighted selected of priorities uses random numbers based on those weights to select an action. If all the weights are 0, there isn't really room for a random number to specifically identify that target. I think the real minimum value should be 1.

**Comment by Brett208** [comment]
Hey, that fixed the bug.

I suppose we should update the SDK documentation to read that a 0 crashes and a 1 is lowest priority.

```C++
void RecordVehReinforceGroup(ScGroup& targetGroup, int priority); // 0 = lowest priority, 0xFFFF = highest
```

Did you think this would be worth patching the function so it turns 0s into 1s or just update the documentation and call it a day.

Thanks for researching this BTW.

-Brett

**Comment by DanRStevens** [comment]
I think we should just update the SDK documentation and call it a day. :)
